config/routes.rb
RsgLinkedinGem::Application.routes.draw do
  get "linkedinuser/show_connections"

  get "jobs/index"

  get "jobs/show"

  devise_for :users

  resources :linkedinuser_connections
  resources :linkedinusers
  resources :companies
  resources :jobs

  match '/linkedin_profile' => "linkedin#linkedin_profile"
  match '/oauth_account' => "linkedin#oauth_account"
  match '/linkedin_oauth_url' => 'linkedin#generate_linkedin_oauth_url'

  match '/jobs_with_connections' => 'jobs#jobs_with_connections'
  match '/companies_with_jobs' => 'companies#companies_with_jobs'
  match '/show_connections' => 'linkedinusers#show_connections'

  match '/companies/:id/company_connections' => 'companies#company_connections', :as => 'company_connections'

  root :to => 'linkedin#index'

end

app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessible :id, :city, :company_id, :link, :posting_date, :state, :title, :logo, :description, :user_id

  belongs_to :company

  def alumni_connections
    alumni_connection_array = []
    # check the company to which the job belongs
    # get all positions at that company
    self.company.positions.each do |position| 
      alumni_connection_array << position if position.belongs_to_alumn?
    end
    alumni_connection_array
  end

  def network_connections
    network_connection_array = []
    # check the company to which the job belongs
    # get all positions at that company
    self.company.positions.each do |position| 
      network_connection_array << position if position.belongs_to_network?
    end
    network_connection_array
  end

  def self.companies_with_jobs
    companies_with_jobs = Job.all.collect { |job| job.company }
  end

  def self.create_all_from_simply_hired
    counter = 1
    url = "http://api.simplyhired.com/a/jobs-api/xml-v2/q-Ruby%20OR%20Rails+Jobs/l-10010/ws-100/pn-1?/ws-100&pshid=48926&ssty=2&cflg=r&jbd=ironedin.jobamatic.com&clip=184.75.101.229"
    max_page_responses = HTTParty.get(url)["sherror"]["error"]["__content__"] rescue "results"
    
    while max_page_responses == "results"
      page_url = "http://api.simplyhired.com/a/jobs-api/xml-v2/q-Ruby%20OR%20Rails+Jobs/l-10010/ws-100/pn-#{counter}?/ws-100&pshid=48926&ssty=2&cflg=r&jbd=ironedin.jobamatic.com&clip=184.75.101.229"
      responses = HTTParty.get(page_url)["shrs"]["rs"]["r"]
      responses.each do |response|
        company_name = response["cn"]["__content__"]
        c = Company.find_or_create_by_company_linkedin_name(company_name)
        j = Job.new
        j.company = c
        j.get_attributes_for_simply_hired(response)
        j.daily_auto_update
      end
      counter += 1
    end
  end

  def get_attributes_for_simply_hired(response)
    self.title        = response["jt"]
    self.posting_date = response["dp"] 
    self.link         = response["src"]["url"]
    self.city         = response["loc"]['cty'] 
    self.state        = response["loc"]["st"]
    self.description  = response["e"]    
  end

  def self.create_all_from_career_builder
    url = "http://api.careerbuilder.com/v1/jobsearch?DeveloperKey=WDTZ00074Z2GPBW05BMD&Keywords=ruby&Location=10010&radius=10&PerPage=100"
    responses = HTTParty.get(url)["ResponseJobSearch"]["Results"]["JobSearchResult"]
    responses.each do |response|
      company_name = response["Company"]
      c = Company.find_or_create_by_company_linkedin_name(company_name)
      j = Job.new
      j.company = c
      j.get_attributes_for_career_builder(response)
      j.daily_auto_update
    end
  end

  def get_attributes_for_career_builder(response)
    self.title        = response["ONetFriendlyTitle"]
    self.posting_date = Date.strptime(response["PostedDate"], "%m/%d/%Y") 
    self.link         = response["JobDetailsURL"]
    location          = response["Location"].split(" - ")
    self.city         = location.first 
    self.state        = location.last 
    self.description  = response["DescriptionTeaser"]
    self.logo         = response["CompanyImageURL"] 
  end
  
  def daily_auto_update
    save

    # if self.posting_date.month == Time.now.month &&
    # self.posting_date.day == Time.now.day
    #   save
    # end
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @jobs }
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @job = Job.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @job }
    end
  end

  def jobs_with_connections
    @jobs = Job.all

    respond_to do |format|
      format.html # jobs_with_connections.html.erb
    end
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/index.html.erb
<h1>Index for Jobs</h1>

<h3>Number of jobs listed: <%= @jobs.size %></h3>

<nav>
  <%= link_to 'All Companies', companies_path %> | <%= link_to 'Companies with Jobs', companies_with_jobs_path %> | <%= link_to 'Jobs with Connections', jobs_with_connections_path %> | <%= link_to 'Alumni Network', show_connections_path %>
</nav>

<div class="row" style="margin-top: 16px;">
  <div class="span10">
    <h1>Jobs</h1>

     <table class="table table-striped">
        <tr>
          <th>Company</th>
          <th>Title</th>
          <th>City</th>
        </tr>        
      <% @jobs.each do |job| %>
        <tr>
          <th><%= link_to job.company.company_linkedin_name, job.company%></th>
          <th><%= link_to job.title, job %></th>
          <th><%= job.city %></th>
        </tr>  
      <% end %>
      </table>
  </div>
</div>
<br>

app/views/jobs/jobs_with_connections.html.erb
<h1>All Jobs with Connections</h1>

<h3>Number of jobs listed: <%= @jobs.size %></h3>

<nav>
  <%= link_to 'All Companies', companies_path %> | <%= link_to 'All Jobs', jobs_path %> | <%= link_to 'Alumni Network', show_connections_path %>
</nav>




<div class="row" style="margin-top: 16px;">
  <div class="span10">
    <h1>Jobs</h1>

     <table class="table table-striped">
        <tr>
          <th>Company</th>
          <th>Title</th>
          <th>City</th>
          <th>Network connections</th>
        </tr>        
      
      <% @counter = 0 %>
      <% @alumni_array = [] %>
      <% @connections_array = [] %>
      <% @jobs.each do |job| %>
        <% if Position.find_by_company_id(job.company.id) != nil %>
          <% unless job.company.id == 1013 %>
            <tr>
              <th><%= link_to job.company.company_linkedin_name, job.company %></th>
              <th><%= link_to job.title, job %></th>
              <th><%= job.city %></th>
              <th><%= job.network_connections.size %></th>
            </tr>
          <% end %>
        <% end %>  
      <% end %>
      </table>
  </div>
</div>

<div class="row" style="margin-top: 16px;">
  <div class="span10">
    <h1>Companies with at least one job and one connection</h1>

     <table class="table table-striped">
        <tr>
          <th>Company</th>
          <th># Jobs</th>
          <th>City</th>
          <th>Network connections</th>
        </tr>        
      
      <% @counter = 0 %>

      <% Company.companies_with_jobs_and_connections.each do |company| %>
          <% unless company.id == 1013 %>
            <tr>
              <th><%= link_to company.company_linkedin_name, company %></th>
              <th><%= company.jobs.size %></th>
              <th>test</th>
              <th>test</th>
            </tr>
          <% end %>
      <% end %>
      </table>
  </div>
</div>





<h3>Number of connections that can help you: <%= @counter %></h3>
<br>

app/views/jobs/show.html.erb
<h1>Job Details</h1>

<nav>
  <%= link_to 'All Companies', companies_path %> | <%= link_to 'Companies with Jobs', companies_with_jobs_path %> | <%= link_to 'All Jobs', jobs_path %> | <%= link_to 'Jobs with Connections', jobs_with_connections_path %> | <%= link_to 'Alumni Network', show_connections_path %>
</nav>

<div class="row" style="margin-top: 16px;">
  <div class="span10">
    <h1>Details</h1>

     <table class="table table-striped">
        <tr>
          <th>Company</th>
          <th>Title (link to posting)</th>
          <th>City</th>
        </tr>        
        <tr>
          <th><%= link_to @job.company.company_linkedin_name, @job.company%></th>
          <th><%= link_to @job.title, @job.link %></th>
          <th><%= @job.city %></th>
        </tr>  
      </table>
  </div>
</div>
<br>